
name: Daily Podcast Broadcast
on:
  schedule:
    - cron: '0 5 * * 1-5' # Runs at 05:00 UTC, Mon-Fri
  workflow_dispatch:
    inputs:
      is_test:
        description: 'Diagnostic Test (5m Tone)'
        required: false
        default: 'false'

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install System Tools
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Dependencies
        run: npm install @google/genai
      - name: Run Headless Station
        env:
          API_KEY: ${{ secrets.API_KEY }}
          IS_TEST: ${{ github.event.inputs.is_test || 'false' }}
        run: npx ts-node headless.ts
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Sundaram Labs Bot"
          git config --global user.email "bot@sundaramlabs.ai"
          git add .
          git commit -m "Broadcast Update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
